// NAVIGATE
export const NAVIGATE = 'NAVIGATE';
export const NAVIGATE_SUCCESS = 'NAVIGATE_SUCCESS';

// USER CONSTANTS
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const USER_INFO = 'USER_INFO';
export const HANDLE_USER_CHANGE = 'HANDLE_USER_CHANGE';
export const HANDLE_USER_CHANGE_SUCCESS = 'HANDLE_USER_CHANGE_SUCCESS';

// POST CONSTANTS
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const READ_POST = 'READ_POST';
export const READ_POST_SUCCESS = 'READ_POST_SUCCESS';
export const GET_SECTION_POSTS = 'GET_SECTION_POSTS';
export const GET_SECTION_POSTS_SUCCESS = 'GET_SECTION_POSTS_SUCCESS';
export const POST_COMMENT = 'POST_COMMENT';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';

// SECTION CONSTANTS
export const GET_SECTIONS = 'GET_SECTIONS';
export const GET_SECTIONS_SUCCESS = 'GET_SECTIONS_SUCCESS';

// RESET
export const RESET = 'RESET'

//ERROR
export const USER_ERROR = 'USER_ERROR'
export const USER_ERROR_SUCCESS = 'USER_ERROR_SUCCESS'
